### ISSUE TITLE
Showing negative

### ISSUE THREAD

**Issue by rmb938** [Waldxn/ZeahRCTracker#3]
Not sure what happened but I went to craft my first set of bloods for the day and the overlay is showing a negative number
![Screenshot_20230730_174505](https://github.com/Waldxn/ZeahRCTracker/assets/544545/9f8604bb-b157-486a-a518-29411f3efab7)

**Comment by Waldxn** [comment]
@rmb938 This is currently being worked on, and should be fixed soon.

**Comment by ChrisWaldenDev** [comment]
https://github.com/Waldxn/ZeahRCTracker/commit/745ca8747b6eba4e43f2ec13d1ed1123466e9c40

Fixed your issue with this commit @rmb938.

**Comment by rmb938** [comment]
Awesome thanks!
